version: "3.8"

services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    env_file: ./.env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQLDB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQLDB_DATABASE}
    ports:
      - "${MYSQLDB_LOCAL_PORT}:${MYSQLDB_DOCKER_PORT}"
    volumes:
      - db:/var/lib/mysql

  app:
    depends_on:
      - mysqldb
    build: .
    restart: on-failure
    env_file: ./.env
    ports:
      - "8082:8082"  # Mapea el puerto 8082 del contenedor al 8082 de tu máquina local
    environment:
      SPRING_APPLICATION_JSON: >
        {
          "spring.datasource.url": "jdbc:mysql://mysqldb:${MYSQLDB_DOCKER_PORT}/${MYSQLDB_DATABASE}?useSSL=false",
          "spring.datasource.username": "${MYSQLDB_USER}",
          "spring.datasource.password": "${MYSQLDB_ROOT_PASSWORD}",
          "spring.jpa.properties.hibernate.dialect": "org.hibernate.dialect.MySQL8InnoDBDialect",
          "spring.jpa.hibernate.ddl-auto": "update"
        }
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    depends_on:
      - mysqldb
    environment:
      PMA_HOST: mysqldb
      MYSQL_ROOT_PASSWORD: ${MYSQLDB_ROOT_PASSWORD}
    ports:
      - "8081:80"

volumes:
  db:
